### PR TITLE
Nh ticket 1

### PR DESCRIPTION
**Pull request by Nick-T-Hansen**
## Overview

Please review the steps below which represents the requirements for tickets 1,2 and 3. Functionality includes employee index, details, and create.

## Steps
1. git fetch --all
1. git checkout nh-ticket-1
1. run app
1. click on employee from the nav bar and confirm you see a list of employees (name and department)
1. click on details of a user and confirm you see name, department, computer, and trainings 
1. go back and create a new employee, confirm there is a populated dropdown menu
1. confirm it is created (and you can see the details) once it sends you back to the main employee screen.

### Notes
1. the new employee will not have a computer or trainings
1. Lorenzo will have multiple trainings
1. you can remove the test employee by rerunning the base database is SSMS

### CODE REVIEW

**Review by ColleenWoolsey — COMMENTED** [review]
Hey Nick ... When I added an Employee and then looked at the details seemed like there was a problem with seeing the details - Something to do with null data ... Perhaps referring to trainings

**Review by leahhoefling — APPROVED** [review]
Wonderful job! Also-- thank you for the detailed steps for this PR

**Review by huntermetts — APPROVED** [review]
Great work bro!

**Review by MaryRemo — APPROVED** [review]
Looks great!

**Review by leahhoefling — APPROVED** [review]
Good!

**Pull request merged**
